runtime: python27
api_version: 1
threadsafe: true
automatic_scaling:
  max_idle_instances: 2 
  
libraries:
- name: ssl
  version: latest
  
env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'true'
  
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

